config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'
  devise_for :users
  resources :books, only: [:create, :index, :edit, :show, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :follows, :followers
    end
    get 'search' => "users#search"
  end
  resources :messages, only: [:show, :create]
  resources :groups, only: [:edit, :show, :create, :update, :index, :new] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end
  root to: "homes#top"
  get '/home/about' => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :group_members, through: :group_users, source: :user

  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def is_owned_by?(user)
    owner_id == user.id
  end

  def include?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.group_members << current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    group = Group.find(params[:id])
    if group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def index
    @groups = Group.all
    @book = Book.new
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image, :owner_id)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= render 'layouts/error',  obj: group %>
<%= form_with model: group do |f| %>
  <div class="field">
    <%= f.label :name, 'グループ名' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :introduction, '紹介文' %><br>
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.label :Image, 'グループ画像' %><br>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  <div class="field">
    <%= f.submit class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_image(50, 50) %></td>
        <td><%= link_to group.name, group_path(group.id) %></td>
        <td><%= group.introduction %></td>
        <td><%= group.group_users.count %></td>
      <% if group.is_owned_by?(current_user) %>
        <td><%= link_to 'Edit', edit_group_path(group.id), class: 'btn btn-success' %> </td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-auto">
      <h1>Editing Group</h1>
      <%= render 'groups/form', obj: @group, group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2">
      <%= render 'books/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1 mx-2">
      <h2>Groups</h2>
      <%= render 'groups/index', groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-auto">
      <h1>Create Group</h1>
      <%= render 'groups/form', obj: @group, group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2">
      <%= render 'books/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1 mx-2">
      <h1>Group Detail</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_image(50, 50) %></td>
            <td><%= @group.name %></td>
          <% @group.group_members.each do |member| %>
            <td><%= member.name %></td>
          <% end %>
          <% if @group.is_owned_by?(current_user) %>
            <td><%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-success' %></td>
            <td><%= link_to 'Notice an Event', new_group_event_notice_path(@group), class: 'btn btn-info' %></td>
          <% else %>
            <% if @group.include?(current_user) %>
              <td><%= link_to 'Leave this group', group_group_users_path(@group), method: :delete, class: 'btn btn-danger' %></td>
            <% else %>
              <td><%= link_to 'Join this group', group_group_users_path(@group), method: :post, class: 'btn btn-success' %></td>
            <% end %>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>