config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'
  devise_for :users
  resources :books, only: [:create, :index, :edit, :show, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :follows, :followers
    end
    get 'search' => "users#search"
  end
  resources :messages, only: [:show, :create]
  resources :groups, only: [:edit, :show, :create, :update, :index, :new] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end
  root to: "homes#top"
  get '/home/about' => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :view_counts, dependent: :destroy
  has_many :group_users, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followeds, through: :reverse_of_relationships, source: :follower

  validates :name, uniqueness: true, length: { minimum:2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followers.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE?', "#{create_at}%"]).count
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followers
  end

  def followers
    user = User.find(params[:id])
    @users = user.followeds
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td><%= user.name %></td>
      <td>フォロー数: <%= user.followers.count %></td>
      <td>フォロワー数: <%= user.followeds.count %></td>
      <% if user != current_user %>
        <% if current_user.following?(user) %>
          <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
        <% else %>
          <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
        <% end %>
      <% end %>
      <td>
        <%= link_to "Show", user_path(user) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_search.html.erb
<h2>検索結果</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-auto">
      <h1>User info</h1>
      <%= render 'layouts/error',  obj: @user %>
      <%= form_with model: @user do |f| %>
        <%= f.label :Name %>
        <%= f.text_field :name %>
        <%= f.label :Image %>
        <%= f.file_field :profile_image, accept: "image/*" %>
        <%= f.label :Introduction %>
        <%= f.text_area :introduction %>
        <%= f.submit 'Update User', class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<% if @users.exists? %>
  <%= render 'users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/follows.html.erb
<h1>Follow Users</h1>
<% if @users.exists? %>
  <%= render 'users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2">
      <%= render 'books/info', user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1 mx-2">
      <h2>Users</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'users/search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2">
      <%= render 'books/info', user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1 mx-2">
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
      <div class="search">
        <%= form_with url: user_search_path(@user), local: false, method: :get do |f| %>
          <%= f.date_field :created_at %>
          <%= f.submit "検索", class: 'btn btn-primary' %>
        <% end %>
      </div>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'users/search', search_book: @search_book %>
        <% end %>
      </div>

      <div class="posts">
        <h2>投稿数の前日比・前週比</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @books.created_days_ago(0).count %></td>
              <td><%= @books.created_days_ago(1).count %></td>
            <% if @books.created_days_ago(1).count == 0 %>
              <td>前日の投稿はなし</td>
            <% else %>
              <td>
                <%= ((@books.created_days_ago(0).count.to_f / @books.created_days_ago(1).count) * 100).round %>%
              </td>
            <% end %>
            </tr>
          </tbody>
        </table>

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今週の投稿数</th>
              <th>前週の投稿数</th>
              <th>前週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @books.created_this_week.count %></td>
              <td><%= @books.created_last_week.count %></td>
            <% if @books.created_last_week.count %>
              <td>前週の投稿はなし</td>
            <% else %>
              <td>
                <%= ((@books.created_this_week.count.to_f / @books.created_last_week.count) * 100).round %>%
              </td>
            <% end %>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="this_week">
        <h2>7日間分の投稿数</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>6日前</th>
              <th>5日前</th>
              <th>4日前</th>
              <th>3日前</th>
              <th>2日前</th>
              <th>1日前</th>
              <th>今日</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @books.created_days_ago(6).count %></td>
              <td><%= @books.created_days_ago(5).count %></td>
              <td><%= @books.created_days_ago(4).count %></td>
              <td><%= @books.created_days_ago(3).count %></td>
              <td><%= @books.created_days_ago(2).count %></td>
              <td><%= @books.created_days_ago(1).count %></td>
              <td><%= @books.created_days_ago(0).count %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div>
        <canvas id="myChart"></canvas>
      </div>

      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

      <script>
        $(document).on('turbolinks:load', function (){
        const ctx = document.getElementById('myChart');
        new Chart(ctx, {
          type: 'line',
          data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [{
              label: '投稿した本の数',
              data: <%= @books.past_week_count %>,
              borderColor: "rgba(0,0,255,1)"
            }],
          },
          options: {
            plugins: {
              title: {
                display: true,
                text: '7日間の投稿数の比較'
              },
            },
              scales: {
                y: {
                  suggestedMin: 0,
                  suggestedMax: 10,
                  stepSize: 1
                }
              },
          },
        });
        });
      </script>
    </div>
  </div>
</div>