config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'
  devise_for :users
  resources :books, only: [:create, :index, :edit, :show, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :follows, :followers
    end
    get 'search' => "users#search"
  end
  resources :messages, only: [:show, :create]
  resources :groups, only: [:edit, :show, :create, :update, :index, :new] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end
  root to: "homes#top"
  get '/home/about' => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }

  scope :created_days_ago, ->(n) { where(created_at: n.days.ago.all_day) }
  scope :created_this_week, -> { where(created_at: Time.current.all_week) }
  scope :created_last_week, -> { where(created_at: Time.current.last_week.all_week) }

  def self.past_week_count
    (0..6).map { |n| created_days_ago(n).count }.reverse
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :group_members, through: :group_users, source: :user

  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def is_owned_by?(user)
    owner_id == user.id
  end

  def include?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :view_counts, dependent: :destroy
  has_many :group_users, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followeds, through: :reverse_of_relationships, source: :follower

  validates :name, uniqueness: true, length: { minimum:2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followers.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = @book.user
      @books = Book.all
      render :index
    end
  end

  def index
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorites).
    sort_by{|x|
      x.favorites.where(created_at: from...to).size}.reverse
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    @user = @book.user
    @book_comment = BookComment.new
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body,)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= render 'layouts/error', obj: book %>
<%= form_with model: book do |f| %>
  <div class="field">
    <%= f.label :Title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Opinion %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
      </td>
      <td>
        <%= link_to book_path(book.id) do %>
          <%= book.title %>
        <% end %>
      </td>
      <td><%= book.body %></td>
      <td class="favorite-btn<%= book.id %>"><%= render 'favorites/favorite_btn', book: book %></td>
      <td class="count">コメント数: <%= render 'book_comments/count', book: book %></td>
      <td>閲覧数: <%= book.view_counts.count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tr><th>name</th><td><%= user.name %></td></tr>
    <tr><th>introduction</th><td><%= user.introduction %></td></tr>
    <tr><th>follows</th><td><%= link_to user.relationships.count, follows_user_path(user) %></td></tr>
    <tr><th>followers</th><td><%= link_to user.reverse_of_relationships.count, followers_user_path(user) %></td></tr>
  </table>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user), method: :post, class: 'btn btn-success' %>
    <% end %>
    <% if current_user.following?(user) && user.following?(current_user) %>
      <%= link_to 'chatを始める', message_path(user.id), class: "ml-3" %>
    <% end %>
  <% else %>
    <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary w-100 text-secondary' do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'form', book: @book %>
      <div class="mt-3">
        <span><%= link_to 'Show', book_path(@book) %> | </span><span><%= link_to 'Back', books_path %></span>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2">
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1 mx-2">
      <h1>Books</h1>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2">
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'form', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1 mx-2">
      <h1>Book detail</h1>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= image_tag @user.get_profile_image(100,100) %>
            <% end %>
            <br>
            <%= link_to user_path(@book.user.id) do %>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book) do %>
              <%= @book.title %>
            <% end %>
          </td>
          <td><%= @book.body %></td>
          <td class="favorite-btn<%= @book.id %>"><%= render 'favorites/favorite_btn', book: @book %></td>
          <td class="count">コメント数: <%= render 'book_comments/count', book: @book %></td>
          <td>閲覧数: <%= @book.view_counts.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-success m-2' %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-danger' %></td>
          <% end %>
        </tr>
      </table>
      <div class="book_comment">
          <%= render 'book_comments/comment', book: @book %>
      </div>
      <div>
        <%= form_with model: [@book, @book_comment], local: false do |f| %>
          <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>